In [12]:
from time import time
from components.dataset_jo import Dataset_subjectDependent as MyDataset
from components.ml import *
from components.preprocessing import *

dataset = MyDataset('data')
segment_lenght = 60 #second
dataset.set_segment(7680//(128*segment_lenght))

Found: 32 files


In [13]:
a,b,c, = dataset.get_data('s01', stimuli=0, return_type='numpy')
a.shape,b.shape,c.shape

((40, 32, 7680), (40,), (40,))

In [10]:
a = None
type(None)

NoneType

In [39]:
count = 0
all_datas, all_labels, all_groups = [],[],[]
for filename in dataset.get_file_list():
    data, labels, groups = dataset.get_data(filename, stimuli=0, return_type='numpy')
    # subj 1 will have groups start from 100 101 102 ... 139
    # subj 2 will have groups start from 200 201 202 ... 239
    # ...
    # subj 32 will have groups start from 3200 3201 3202 ... 3239
    groups = int(filename[1:])*100 +  groups
    # print(filename, int(filename[1:])*100 +  groups)
    all_datas.append(data)
    all_labels.append(labels)
    all_groups.append(groups.reshape(-1,1))
all_datas = np.vstack(all_datas)
all_labels = np.vstack(all_labels).reshape(-1)
all_groups = np.vstack(all_groups).reshape(-1)

((6400, 32, 1536), (6400,), (6400,))

In [9]:
import numpy as np
C_range = np.logspace(-2, 10, 7)
gamma_range = np.logspace(-9, 3, 7)
print(C_range)
print(gamma_range)

[1.e-02 1.e+00 1.e+02 1.e+04 1.e+06 1.e+08 1.e+10]
[1.e-09 1.e-07 1.e-05 1.e-03 1.e-01 1.e+01 1.e+03]


In [1]:
import pandas as pd
pd.read_csv("./output/gridSearch/s01-1.csv")

Unnamed: 0  mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0             0       0.006463      0.012401         0.000465        0.000161   
1             1       0.001635      0.002207         0.000607        0.000828   
2             2       0.000688      0.000172         0.000341        0.000091   
3             3       0.000888      0.000110         0.000350        0.000052   
4             4       0.000859      0.000140         0.000360        0.000076   
..          ...            ...           ...              ...             ...   
177         177       0.000744      0.000091         0.000382        0.000061   
178         178       0.000819      0.000153         0.000491        0.000110   
179         179       0.000659      0.000059         0.000350        0.000035   
180         180       0.000716      0.000142         0.000372        0.000058   
181         181       0.000808      0.000208         0.000397        0.000055   

          param_C param_kernel  param_gamma  \
0    1.000000e-02       linear          NaN   
1    1.000000e-01       linear          NaN   
2    1.000000e+00       linear          NaN   
3    1.000000e+01       linear          NaN   
4    1.000000e+02       linear          NaN   
..            ...          ...          ...   
177  1.000000e+10          rbf          0.1   
178  1.000000e+10          rbf          1.0   
179  1.000000e+10          rbf         10.0   
180  1.000000e+10          rbf        100.0   
181  1.000000e+10          rbf       1000.0   

                                                params  split0_test_score  \
0                      {'C': 0.01, 'kernel': 'linear'}               0.25   
1                       {'C': 0.1, 'kernel': 'linear'}               0.25   
2                       {'C': 1.0, 'kernel': 'linear'}               1.00   
3                      {'C': 10.0, 'kernel': 'linear'}               0.50   
4                     {'C': 100.0, 'kernel': 'linear'}               0.50   
..                                                 ...                ...   
177  {'C': 10000000000.0, 'gamma': 0.1, 'kernel': '...               0.75   
178  {'C': 10000000000.0, 'gamma': 1.0, 'kernel': '...               0.25   
179  {'C': 10000000000.0, 'gamma': 10.0, 'kernel': ...               0.25   
180  {'C': 10000000000.0, 'gamma': 100.0, 'kernel':...               0.25   
181  {'C': 10000000000.0, 'gamma': 1000.0, 'kernel'...               0.25   

     ...  split1_train_score  split2_train_score  split3_train_score  \
0    ...               0.625             0.59375             0.59375   
1    ...               0.625             0.59375             0.62500   
2    ...               0.875             0.87500             0.87500   
3    ...               1.000             1.00000             1.00000   
4    ...               1.000             1.00000             1.00000   
..   ...                 ...                 ...                 ...   
177  ...               1.000             1.00000             1.00000   
178  ...               1.000             1.00000             1.00000   
179  ...               1.000             1.00000             1.00000   
180  ...               1.000             1.00000             1.00000   
181  ...               1.000             1.00000             1.00000   

     split4_train_score  split5_train_score  split6_train_score  \
0               0.56250             0.59375             0.65625   
1               0.56250             0.59375             0.65625   
2               0.90625             0.81250             0.93750   
3               1.00000             1.00000             1.00000   
4               1.00000             1.00000             1.00000   
..                  ...                 ...                 ...   
177             1.00000             1.00000             1.00000   
178             1.00000             1.00000             1.00000   
179             1.00000             1.00000             1.00000   
180    

In [2]:
import numpy as np
C_range = np.logspace(-2, 10, 13)
C_range

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05,
       1.e+06, 1.e+07, 1.e+08, 1.e+09, 1.e+10])

In [ ]:
for filename in dataset.get_file_list():
    start = time()
    data, labels, groups = dataset.get_data(filename, stimuli=MyDataset.STIMULI_AROUSAL, return_type='numpy')
    X = DE(data)
    cv_scores = train_model_segment_first(X, labels.reshape(-1), groups)

    print(f"\tAROUSAL-{filename}|10-CV={round(cv_scores.mean(),5)}|STD={round(cv_scores.std(),5)}|Time spend={time() - start}")


In [ ]:
# import numpy as np
# from sklearn.svm import SVC
# from sklearn.model_selection import StratifiedGroupKFold,GridSearchCV
# from sklearn.svm import SVC
# from IPython.display import display
# import pandas as pd

# def train_model_segment_first(X,y,groups) -> list:
#     """
#         X: The sample set with shape of (n_samples, n_features)
#         y: The labels with shape of (n_samples,)
#         groups: A data indicates which trials the samples belong to (n_samples,)
#     """
#     # Here we have to perform double cross validation.
#     # The idea is we will do 10-CV
#     # The option we have to choose is split-first or segment-first
#     # If we do "Split-first", then models learn little record of every trial
#     # If we doe "Segment-first", then models learn 90% of trials and test on 10%
#     # This segment-first can be done using "group" argument during split.
#     n_split_outter = 10
#     cv_outter = StratifiedGroupKFold(n_splits=n_split_outter, shuffle=False)
#     accs = []
#     for epoch, (idxs_train, idxs_test) in enumerate(cv_outter.split(X,y,groups)):
#         print(f"BEGIN EPOCH: {epoch+1}/{n_split_outter}")
#         X_train, X_test = X[idxs_train], X[idxs_test]
#         y_train, y_test = y[idxs_train], y[idxs_test]
#         groups_train, groups_test = groups[idxs_train], groups[idxs_test]
#         assert set(groups_train).isdisjoint(set(groups_test)),f"Contaminated.\ngroups_train:{groups_train}\ngroups_test:{groups_test}"

#         model = build_model(X_train,y_train,groups_train)
        
#         # Evaluation
#         predict = model.predict(X_test)
#         acc = sum(predict == y_test)
#         accs.append(acc)
#     return accs

# def build_model(X,y,groups) -> SVC:
#     """
#         This function will only optimized models
#     """
#     n_split = 9
#     cv = StratifiedGroupKFold(n_splits=n_split, shuffle=True, random_state=42)
#     tuned_parameters = [
#             {"kernel": ["linear"], "C": [1, 10, 100, 1000]},
#             {"kernel": ["rbf"],    "C": [1, 10, 100, 1000], "gamma": [1e-3, 1e-4]},
#         ]
#     grid = GridSearchCV(SVC(), param_grid=tuned_parameters, cv=cv, n_jobs=-1, refit=True, verbose=4, return_train_score=True)
#     grid.fit(X=X, y=y, groups=groups)
#     df = pd.DataFrame(grid.cv_results_)
#     display(df)
#     return grid.best_estimator_